/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package testengine;

import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Er. Ved Prakash Arya
 */
public class SetQuestion extends javax.swing.JFrame {

    /**
     * Creates new form SetQuestion
     */
    public SetQuestion() {
       // setUndecorated(true);
        initComponents();
    }
     String question,opA,opB,opC,opD,Tans;
     String A,B,C,D;
     static String sub;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        select = new javax.swing.JComboBox();
        QField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        AField1 = new javax.swing.JTextField();
        BField1 = new javax.swing.JTextField();
        CField1 = new javax.swing.JTextField();
        DField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TickAnswer1 = new javax.swing.JButton();
        Done = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        timev = new javax.swing.JLabel();
        datev = new javax.swing.JLabel();
        ARadioButton = new javax.swing.JRadioButton();
        DRadioButton = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        Clear = new javax.swing.JButton();
        BRadioButton = new javax.swing.JRadioButton();
        CRadioButton = new javax.swing.JRadioButton();
        Logout = new javax.swing.JButton();
        Preview = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        logo.setBackground(new java.awt.Color(255, 255, 204));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("TEST ENGINE");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 255));
        jLabel11.setText("Subject");

        select.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        select.setForeground(new java.awt.Color(0, 255, 51));
        select.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select-", "cpp", "java", "javascript", "php", "python", "html" }));
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        QField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                QFieldFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                QFieldFocusGained(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 255));
        jLabel12.setText("Type Q.");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 255));
        jLabel13.setText("Choice");

        AField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                AField1FocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                AField1FocusGained(evt);
            }
        });

        BField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BField1FocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                BField1FocusGained(evt);
            }
        });

        CField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CField1FocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                CField1FocusGained(evt);
            }
        });

        DField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DField1FocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                DField1FocusGained(evt);
            }
        });

        jLabel14.setText("(A)");

        jLabel15.setText("(B)");

        jLabel16.setText("(C)");

        jLabel17.setText("(D)");

        TickAnswer1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TickAnswer1.setForeground(new java.awt.Color(255, 0, 0));
        TickAnswer1.setText("Pick Answer");
        TickAnswer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TickAnswer1MouseReleased(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TickAnswer1MousePressed(evt);
            }
        });
        TickAnswer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TickAnswer1ActionPerformed(evt);
            }
        });

        Done.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Done.setForeground(new java.awt.Color(0, 153, 0));
        Done.setText("Done");
        Done.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DoneMouseReleased(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DoneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DoneMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DoneMousePressed(evt);
            }
        });
        Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon.jpg"))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconColor.jpg"))); // NOI18N

        timev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timev.setForeground(new java.awt.Color(153, 0, 153));
        timev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timev.setText("Time :");

        datev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        datev.setForeground(new java.awt.Color(153, 0, 153));
        datev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datev.setText("Date :");

        buttonGroup1.add(ARadioButton);
        ARadioButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N

        buttonGroup1.add(DRadioButton);
        DRadioButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Tick Answer");

        Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clear.setForeground(new java.awt.Color(153, 0, 204));
        Clear.setText("Clear All");
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClearMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClearMouseEntered(evt);
            }
        });
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        buttonGroup1.add(BRadioButton);
        BRadioButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N

        buttonGroup1.add(CRadioButton);
        CRadioButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N

        Logout.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(0, 153, 0));
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
        });
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Preview.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        Preview.setForeground(new java.awt.Color(255, 51, 0));
        Preview.setText("Preview");
        Preview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PreviewMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PreviewMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PreviewMouseEntered(evt);
            }
        });
        Preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(320, 320, 320))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(QField))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(CField1)
                                                    .addComponent(AField1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(BField1)
                                                    .addComponent(DField1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel16))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(DRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                                .addComponent(CRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ARadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(BRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(timev, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(logo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(datev, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TickAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(324, 324, 324)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Preview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Done, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Clear)
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datev, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(timev, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Preview)
                        .addGap(18, 18, 18)
                        .addComponent(Logout)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(TickAnswer1)
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(ARadioButton))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)
                                        .addGap(25, 25, 25))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(BRadioButton)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(CRadioButton))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(11, 11, 11))
                            .addComponent(DRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Done)
                            .addComponent(Clear))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(912, 559));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectActionPerformed

    private void QFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_QFieldFocusLost

        QField.setBackground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_QFieldFocusLost

    private void QFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_QFieldFocusGained
        QField.setBackground(Color.lightGray);
        // TODO add your handling code here:
    }//GEN-LAST:event_QFieldFocusGained

    private void AField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AField1FocusLost

        AField1.setBackground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_AField1FocusLost

    private void AField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AField1FocusGained
        AField1.setBackground(Color.lightGray);        // TODO add your handling code here:
    }//GEN-LAST:event_AField1FocusGained

    private void BField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BField1FocusLost

        BField1.setBackground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_BField1FocusLost

    private void BField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BField1FocusGained

        BField1.setBackground(Color.lightGray);// TODO add your handling code here:
    }//GEN-LAST:event_BField1FocusGained

    private void CField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CField1FocusLost

        CField1.setBackground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_CField1FocusLost

    private void CField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CField1FocusGained

        CField1.setBackground(Color.lightGray);// TODO add your handling code here:
    }//GEN-LAST:event_CField1FocusGained

    private void DField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DField1FocusLost

        DField1.setBackground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_DField1FocusLost

    private void DField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DField1FocusGained

        DField1.setBackground(Color.lightGray);// TODO add your handling code here:
    }//GEN-LAST:event_DField1FocusGained

    private void TickAnswer1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TickAnswer1MouseReleased

        TickAnswer1.setBackground(Color.lightGray);   // TODO add your handling code here:
    }//GEN-LAST:event_TickAnswer1MouseReleased

    private void TickAnswer1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TickAnswer1MousePressed

        TickAnswer1.setBackground(Color.green);   // TODO add your handling code here:
    }//GEN-LAST:event_TickAnswer1MousePressed

    private void TickAnswer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TickAnswer1ActionPerformed
        A=AField1.getText();
        B=BField1.getText();
        C=CField1.getText();
        D=DField1.getText();
        ARadioButton.setText(A);
        BRadioButton.setText(B);
        CRadioButton.setText(C);
        DRadioButton.setText(D);

    }//GEN-LAST:event_TickAnswer1ActionPerformed

    private void DoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoneMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_DoneMouseReleased

    private void DoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoneMouseEntered
        Done.setBackground(Color.yellow);
        // TODO add your handling code here:
    }//GEN-LAST:event_DoneMouseEntered

    private void DoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoneMouseExited

        Done.setBackground(Color.gray);
        // TODO add your handling code here:
    }//GEN-LAST:event_DoneMouseExited

    private void DoneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoneMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoneMousePressed

     public void setPaper(){
         
         question = QField.getText();
         opA = AField1.getText();
         opB = BField1.getText();
         opC = CField1.getText();
         opD = DField1.getText();
    }
    private void DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneActionPerformed
        sub= (String)select.getSelectedItem();
        setPaper();
        if(ARadioButton.isSelected()){
            Tans=ARadioButton.getText();
        }
        if(BRadioButton.isSelected()){
            Tans=BRadioButton.getText();
        }
        if(CRadioButton.isSelected()){
            Tans=CRadioButton.getText();
        }
        if(DRadioButton.isSelected()){
            Tans=DRadioButton.getText();
        }
        DBPaper vset = new DBPaper();
        String q1="INSERT INTO `question`.`"+sub+"` (`Q`, `A`, `B`, `C`, `D`, `Ans`)";
        String q2=" VALUES ('"+question+"', '"+opA+"', '"+opB+"', '"+opC+"', '"+opD+"', '"+Tans+"');";
        String query=q1+q2;
        vset.setData(query);
        try {
            vset.con.close();
        }
        catch(Exception ex){

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_DoneActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        QField.setText("");
        AField1.setText("");
        BField1.setText("");
        CField1.setText("");
        DField1.setText("");
        ARadioButton.setText("");
        BRadioButton.setText("");
        CRadioButton.setText("");
        DRadioButton.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_ClearActionPerformed

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        Logout.setBackground(Color.magenta);
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked

        Logout.setBackground(Color.ORANGE);// TODO add your handling code here:
    }//GEN-LAST:event_LogoutMouseClicked

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited

        Logout.setBackground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_LogoutMouseExited

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed

        HomePage HP2= new HomePage();
        this.setVisible(false);
        HP2.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void PreviewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PreviewMouseEntered
       Preview.setBackground(Color.ORANGE); // TODO add your handling code here:
    }//GEN-LAST:event_PreviewMouseEntered

    private void PreviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PreviewMouseClicked
        Preview.setBackground(Color.CYAN);// TODO add your handling code here:
    }//GEN-LAST:event_PreviewMouseClicked

    private void PreviewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PreviewMouseExited
        Preview.setBackground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_PreviewMouseExited

    private void PreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviewActionPerformed
        
         sub= (String)select.getSelectedItem();
        Admin ad = new Admin();
        ad.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_PreviewActionPerformed

    private void ClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseEntered
        Clear.setBackground(Color.yellow);   // TODO add your handling code here:
    }//GEN-LAST:event_ClearMouseEntered

    private void ClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseExited
         Clear.setBackground(Color.white); 
    }//GEN-LAST:event_ClearMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

         Thread clock = new Thread(){
          public void run(){
               
              for (;;){
                 Date d = new Date();
                 int hr ,min,sec ;
                 hr= d.getHours();
                 min= d.getMinutes();
                 sec = d.getSeconds();
              String formTime=("Time:- "+(hr+":")+(min+":")+(sec+"")); 
              timev.setText(formTime);
              try{
                 
                    sleep(1000);
                 
              }
              catch(Exception ex){
                  JOptionPane.showMessageDialog(null, "Error"+ex);
              }
              
          }
          }
          
      };
        clock.start();
       Calander ved = new Calander();
       ved.dateDisplay();
       datev.setText(ved.formDate);  
            // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetQuestion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AField1;
    private javax.swing.JRadioButton ARadioButton;
    private javax.swing.JTextField BField1;
    private javax.swing.JRadioButton BRadioButton;
    private javax.swing.JTextField CField1;
    private javax.swing.JRadioButton CRadioButton;
    private javax.swing.JButton Clear;
    private javax.swing.JTextField DField1;
    private javax.swing.JRadioButton DRadioButton;
    private javax.swing.JButton Done;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Preview;
    private javax.swing.JTextField QField;
    private javax.swing.JButton TickAnswer1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel datev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox select;
    private javax.swing.JLabel timev;
    // End of variables declaration//GEN-END:variables
}
